# Autogenerated Answer File

q1 = {
  'question': 'What HTML element usually starts and ends the document?',
  'a': '<html> and <html>',
  'b': '<HTML> and </HTML>',
  'c': '<html> and </html>',
  'd': 'PAGE_START and PAGE_END',
  'answer': 'C',
}
q2 = {
  'question': 'Which line of code defines a VALID javascript variable?',
  'a': 'var hello = "WORLD";',
  'b': 'hello = "WORLD";',
  'c': '$hello = string "WORLD";',
  'd': 'hello <= "WORLD";',
'answer': 'A',
}
q3 = {
  'question': 'What does PHP stand for?',
  'a': 'Professional Home Page Tools',
  'b': 'Professional Hierarchial Processing Tools',
  'c': 'Pretty Hello PHP Stuff',
  'd': 'PHP',
  'answer': 'D',
}
q4 = {
  'question': 'What does <script> do?',
  'a': 'Run TypeScript',
  'b': 'Run HTMLScript',
  'c': 'Run JavaScript',
  'd': 'Run PHP',
  'answer': 'C',
}
q5 = {
  'question': 'What does HTTP stand for?',
  'a': 'Hierarchial TypeScript Telenetwork Processing ',
  'b': 'HyperText Transfer Protocol',
  'c': 'HTMLScript Technology Telenetwork Protocol',
  'd': 'Hello Tech-enthusiastic TechnoDot - Programmer',
  'answer': 'C',
}
q6 = {
  'question': 'Which answer contains all valid HTML tags?',
  'a': '<html>, <head>, <script>, <screen>',
  'b': '<body>, <ul>, <br>, <td>',
  'c': '<css>, <js>, <php>, <network>',
  'd': '<techno>, <dot>, <is>, <awesome>',
  'answer': 'B',
}
q7 = {
  'question': 'Why is HTMLScript awesome?',
  'a': 'Trick question',
  'b': 'Because it has HTML in it\'s name',
  'c': 'Because it is another object-oriented programming language with built-in support for HTML and was made by the ICANN',
  'd': 'WHO CARES??? IT JUST EXISTS!!',
  'answer': 'A',
}

q = [q1, q2, q3, q4, q5, q6, q7]
